micronaut:
  application:
    name: wst-si
datasources:
  default:
    url: ${DB_URL:`jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}
    driverClassName: ${DB_DRIVER:`org.h2.Driver`}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:''}
    schema-generate: ${DB_SCHEMA_GENERATE:CREATE_DROP}
    dialect: ${DB_DIALECT:H2}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: ${DB_AUTO_DDL:update}
        show_sql: ${DB_SHOW_SQL:true}
        format_sql: ${DB_FORMAT_SQL:true}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  server:
    port: ${GRPC_PORT:50051}
    keep-alive-time: 3h
    max-inbound-message-size: 1024
  channels:
    wstMainRead:
      address: ${WST_MAIN_CHANNEL:`localhost:50049`}
      plaintext: true
      max-retry-attempts: 10
